### ISSUE TITLE
Unable to open PDF with error message about API key

### ISSUE THREAD

**Issue by TromboneEngineer** [mukulpatnaik/researchgpt#15]
Error: Request to server failed. Please make sure your API key is correct. Close this tab and try again. Sorry for the inconvenience!

I have tried adding my (new) API key multiple times, but every time it just gives this error after uploading a PDF to https://researchgpt.ue.r.appspot.com/

**Comment by SonWY2** [comment]
I'm facing the same issue as above, even after getting a new API KEY and trying it, it's not possible.
Tried demo site and local clone (with environment variables set) and it was the same.

**Comment by JiyangZhang** [comment]
same here

**Comment by mcastillo109** [comment]
I haven't tired the demo site, but used the local clone. 

I got the API KEY error too so I put the os.environ['OPENAI_API_KEY'] = 'your api key' directly underneath the if __name__ == '__main__': (line 186) in the main-local.py file and it worked.

**Comment by changh95** [comment]
> I haven't tired the demo site, but used the local clone.
> 
> I got the API KEY error too so I put the os.environ['OPENAI_API_KEY'] = 'your api key' directly underneath the if **name** == '**main**': (line 186) in the main-local.py file and it worked.

Thanks! This worked!

**Comment by maxsu** [comment]
For `main-local.py` to run properly, `OPENAI_API_KEY` has to be exported in the shell were you start `main-local.py`. This should fix the issue:

```bash
OPENAI_API_KEY="your api key here" python main-local.py
```


To fix this issue for future users, the Readme's local example should show how to export the environment variable:

```bash
export OPENAI_API_KEY="your api key"
python main-local.py
```

or

```bash
export OPENAI_API_KEY="your api key" python main-local.py
````

It helps to spell it out because bash is a confusing about variable assignment vs exporting. For example, the following code assigns the variable into the shell's local context but fails to export the variable into the python process' context:

```bash
OPENAI_API_KEY="your api key"
python main-local.py
```

Finally, there are two other solutions:
1. Parse the API key from a config.toml file
1. Parse the API key as a command line arg

These are simpler for most users to understand than vs environment vars. However, they're a bit harder to code than the environment variable solution.

**Comment by SonWY2** [comment]
I had to run the source on my company's proxy network, which was a bit of a hassle and I just wanted to try out the demo site. Anyway, I got it up and running with your kind instructions and `main-local.py`. Thank you very much!

**Comment by mukulpatnaik** [comment]
Hi @TromboneEngineer sorry to hear you're having issues with the key. Unfortunately because of the fact that the demo runs everything locally in your browser (due to privacy and security reasons regarding keeping the open ai key local) it is really hard for me to debug what the issue is.

To figure out what's going on you would need to open the network tab in the inspect tool and see which call is failing. Let me know if you're able to do this and I can help figure out what's going wrong. Thanks :)

**Comment by mukulpatnaik** [comment]
@changh95 @maxsu thanks for helping out here. I should make it clearer in the README how to handle the API key locally.

**Comment by maxsu** [comment]
@TromboneEngineer - I started a pull request to resolve the issue for future users.  Can you please visit #37 and confirm if my description is accurate?

**Comment by mukulpatnaik** [comment]
Hi @maxsu thanks for the pull request, however, I recently pushed a major refactor to the code and updated the README as well so it won't be necessary. I appreciate your contribution though!
