### ISSUE TITLE
How to improve / give feedback

### ISSUE THREAD

**Issue by Z-KN** [mukulpatnaik/researchgpt#16]
It seems understanding of papers can be totally wrong... lol
![Issue](https://user-images.githubusercontent.com/50490656/221756728-b38642b7-74fb-4a93-82e2-d2189511a136.png)
Or make no sense...
![Issue2](https://user-images.githubusercontent.com/50490656/221757517-3901f912-983b-495b-a37b-41206b3b95e7.png)

**Comment by endolith** [comment]
Same as https://github.com/mukulpatnaik/researchgpt/issues/17

**Comment by mukulpatnaik** [comment]
Hi @Z-KN @endolith This is not ideal but asking it questions like "what is the main idea of this paper" would not necessarily return embeddings related to what you are asking. This tool is more for asking more specific questions regarding the contents of the paper or asking any doubts like phrases or concepts you don't understand.

Saying something like "hello" will definitely return nonsense every time due to how embeddings work.
