### ISSUE TITLE
No results displayed after loading URL

### ISSUE THREAD

**Issue by ProgramItUp** [mukulpatnaik/researchgpt#2]
From a Windows 10 desktop, running in PowerShell, in a Conda virtual environment, I tried the same URL you did in your demo 
https://arxiv.org/pdf/1706.03762.pdf but was not successful.  
The UI continues to display the message "Loading..."

Here is the output from the command line:

10.20.30.40 - - [15/Feb/2023 10:59:57] "GET / HTTP/1.1" 200 -
{'Date': 'Wed, 15 Feb 2023 16:00:41 GMT', 'Server': 'Apache', 'Strict-Transport-Security': 'max-age=31536000', 'Set-Cookie': 'browser=12.46.106.164.1676476842433583; path=/; max-age=946080000; domain=.arxiv.org', 'Last-Modified': 'Thu, 07 Dec 2017 01:03:18 GMT', 'ETag': '"16bf6527-219864-55fb5a236f4fb"', 'Accept-Ranges': 'bytes', 'Content-Length': '2201700', 'Access-Control-Allow-Origin': '*', 'Keep-Alive': 'timeout=8, max=100', 'Connection': 'Keep-Alive', 'Content-Type': 'application/pdf'}
Parsing paper
Total number of pages: 15
Done parsing paper
Creating dataframe
Done creating dataframe
Calculating embeddings
Done calculating embeddings
Done processing pdf
10.20.30.40 - - [15/Feb/2023 11:00:53] "POST /download_pdf HTTP/1.1" 200 -

**Comment by ProgramItUp** [comment]
I also tried the same process with Ubuntu 20.04 and get the same result.
The initial webpage continues to display "Loading..." even after the .pdf has been loaded and processed.

**Comment by mukulpatnaik** [comment]
@ProgramItUp This issue seems to be due to the cors proxy I was using 'https://api.codetabs.com/v1/proxy?quest=' has unforttunately been taken down. You can try removing these proxy links from the js and py files, my latest [commit](https://github.com/mukulpatnaik/researchgpt/commit/5de9b2341d0b12795f8cc4b467e5341af2d65640) has done exactly that so you could run git pull as well. Please let me know if this works!
