### ISSUE TITLE
Request to server failed. Please refresh try uploading a copy of the pdf instead. Sorry for the inconvenience!

### ISSUE THREAD

**Issue by gleb-roma** [mukulpatnaik/researchgpt#27]
I open the link from README and upload a pdf that I previously downloaded from here
`https://home.uchicago.edu/~amshaikh/webfiles/multiplecar.pdf`

I get an error in the top right corner 

`Error: Request to server failed. Please refresh try uploading a copy of the pdf instead. Sorry for the inconvenience!`

The point is that I *did* upload a copy of pdf. 

Chrome, MacOS

**Comment by gleb-roma** [comment]
Screenshot: ![Screen Shot 2023-03-03 at 9 08 20 AM](https://user-images.githubusercontent.com/3375095/222742316-ba66e99e-dfc4-45b3-9e48-b8b7f5e84acc.png)

**Comment by mukulpatnaik** [comment]
Hi @gleb-roma sorry to hear you're having issues with the demo. Unfortunately because of the fact that the demo runs everything locally in your browser (due to privacy and security reasons regarding keeping the open ai key local) it is really hard for me to debug what the issue is.

To figure out what's going on you would need to open the network tab in the inspect tool and see which call is failing. Let me know if you're able to do this and I can help figure out what's going wrong. Thanks :)

**Comment by zhuzhunvhai2000** [comment]
me too!

**Comment by mukulpatnaik** [comment]
Hi all, @gleb-roma @Ariiiiit sorry for the late response, I recently pushed a major refactor of the code, you should not be facing any of these same issues now. Thanks for trying it and let me know if you have any further questions!
